name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, windows-11-arm]
        dotnet-version: ['8.0.x', '9.0.x']
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET ${{ matrix.dotnet-version }}
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ matrix.dotnet-version }}
    - name: Restore dependencies
      run: dotnet restore EFCoreFluent
    - name: Build
      run: dotnet build EFCoreFluent --no-restore -c Release
    - name: Test
      run: dotnet test EFCoreFluent/EFCoreFluent.sln --no-build -c Release
    - name: Publish Artifact
      if: matrix.os == 'ubuntu-latest' && matrix.dotnet-version == '8.0.x'
      uses: actions/upload-artifact@v4
      with:
        name: Package
        path: "EFCoreFluent/src/EFCoreFluent/bin/Release/**.nupkg"
    
    
