name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    strategy:
      matrix:
        # os: [ubuntu-latest, windows-latest, windows-11-arm]
        os: [windows-latest, windows-11-arm] # Target x64 and arm64 on Windows
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET 9
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'
    - name: Restore dependencies
      run: dotnet restore EFCoreFluent
    - name: Build
      run: dotnet build EFCoreFluent --no-restore -c Release
    - name: Test
      run: dotnet test EFCoreFluent/EFCoreFluent.sln --no-build -c Release
    - name: Publish Artifact
      if: matrix.os == 'ubuntu-latest' && matrix.dotnet-version == '8.0.x'
      uses: actions/upload-artifact@v4
      with:
        name: Package
        path: "EFCoreFluent/src/EFCoreFluent/bin/Release/**.nupkg"
    
    
